<a href="https://colab.research.google.com/github/palayushi293/crop_reccomend/blob/main/crop_recoomendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

python3: can't open file '/content/crop.py': [Errno 2] No such file or directory


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
path="/content/drive/MyDrive/Crop_recommendation (2).csv"
df=pd.read_csv(path)

In [ ]:
df.head()

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [ ]:
df.describe()

N            P            K  temperature     humidity  \
count  2200.000000  2200.000000  2200.000000  2200.000000  2200.000000   
mean     50.551818    53.362727    48.149091    25.616244    71.481779   
std      36.917334    32.985883    50.647931     5.063749    22.263812   
min       0.000000     5.000000     5.000000     8.825675    14.258040   
25%      21.000000    28.000000    20.000000    22.769375    60.261953   
50%      37.000000    51.000000    32.000000    25.598693    80.473146   
75%      84.250000    68.000000    49.000000    28.561654    89.948771   
max     140.000000   145.000000   205.000000    43.675493    99.981876   

                ph     rainfall  
count  2200.000000  2200.000000  
mean      6.469480   103.463655  
std       0.773938    54.958389  
min       3.504752    20.211267  
25%       5.971693    64.551686  
50%       6.425045    94.867624  
75%       6.923643   124.267508  
max       9.935091   298.560117

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   N            2200 non-null   int64  
 1   P            2200 non-null   int64  
 2   K            2200 non-null   int64  
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object 
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB


In [ ]:
import numpy as np

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
df.isna().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [ ]:
x=df.drop("label",axis=1)

In [ ]:
y=df["label"]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn.utils import resample

if x_train.shape[0] > y_train.shape[0]:
    y_train = resample(y_train, replace=True, n_samples=x_train.shape[0])
elif y_train.shape[0] > x_train.shape[0]:
    x_train = resample(x_train, replace=True, n_samples=y_train.shape[0])

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2,random_state=42)

In [ ]:
x_train.shape

(1760, 7)

In [ ]:
x_train.shape

(1760, 7)

In [ ]:
y_train.shape

(1760,)

In [ ]:
x_train.shape

(1760, 7)

In [ ]:
y_train.shape

(1760,)

In [ ]:
print(len(x))
print(len(y))

2200
2200


In [ ]:
x

N   P   K  temperature   humidity        ph    rainfall
0      90  42  43    20.879744  82.002744  6.502985  202.935536
1      85  58  41    21.770462  80.319644  7.038096  226.655537
2      60  55  44    23.004459  82.320763  7.840207  263.964248
3      74  35  40    26.491096  80.158363  6.980401  242.864034
4      78  42  42    20.130175  81.604873  7.628473  262.717340
...   ...  ..  ..          ...        ...       ...         ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507
2196   99  15  27    27.417112  56.636362  6.086922  127.924610
2197  118  33  30    24.131797  67.225123  6.362608  173.322839
2198  117  32  34    26.272418  52.127394  6.758793  127.175293
2199  104  18  30    23.603016  60.396475  6.779833  140.937041

[2200 rows x 7 columns]

In [ ]:
c_summary=pd.pivot_table(df,index=['label'],aggfunc='mean')

In [ ]:
c_summary

K       N       P   humidity        ph    rainfall  temperature
label                                                                      
0      199.89   20.80  134.22  92.333383  5.929663  112.654779    22.630942
1       50.05  100.23   82.01  80.358123  5.983893  104.626980    27.376798
2       19.24   40.02   67.47  65.118426  7.133952   67.884151    29.973340
3       79.92   40.09   67.79  16.860439  7.336957   80.058977    18.872847
4       30.59   21.98   16.93  94.844272  5.976562  175.686646    27.409892
5       29.94  101.20   28.74  58.869846  6.790308  158.066295    25.540477
6       19.56  117.77   46.24  79.843474  6.912675   80.398043    23.988958
7      200.11   23.18  132.53  81.875228  6.025937   69.611829    23.849575
8       39.99   78.40   46.86  79.639864  6.732778  174.792798    24.958376
9       20.05   20.75   67.54  21.605357  5.749411  105.919778    20.115085
10      19.41   18.77   68.36  64.804785  6.927932   45.680454    24.509052
11      19.79   77.76   48.44  65.092249  6.245190   84.766988    22.389204
12      29.92   20.07   27.18  50.156573  5.766373   94.704515    31.208770
13      20.23   21.44   48.01  53.160418  6.831174   51.198487    28.194920
14      19.87   20.99   47.28  85.499975  6.723957   48.403601    28.525775
15      50.08  100.32   17.72  92.342802  6.358805   24.689952    28.663066
16      10.01   19.58   16.55  92.170209  7.016957  110.474969    22.765725
17      50.04   49.88   59.05  92.403388  6.741442  142.627839    33.723859
18      20.29   20.73   67.73  48.061633  5.794175  149.457564    27.741762
19      40.21   18.87   18.75  90.125504  6.429172  107.528442    21.837842
20      39.87   79.89   47.58  82.272822  6.425471  236.181114    23.689332
21      50.22   99.42   17.00  85.160375  6.495778   50.786219    25.591767

In [ ]:
y_train.shape

(1760,)

SCALING THE FEATURES USING MINMAX SCALAR


In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
mms.fit(x_train)

MinMaxScaler()

In [ ]:
x_train=mms.transform(x_train)

In [ ]:
x_test=mms.transform(x_test)

In [ ]:
x_test

array([[0.72142857, 0.08571429, 0.21      , ..., 0.93872187, 0.41682113,
        0.021381  ],
       [0.7       , 0.02142857, 0.23      , ..., 0.84296447, 0.42837304,
        0.10449492],
       [0.42142857, 0.40714286, 0.22      , ..., 0.92264534, 0.5344578 ,
        0.33938901],
       ...,
       [0.86428571, 0.3       , 0.055     , ..., 0.75864563, 0.6560289 ,
        0.18741185],
       [0.82857143, 0.33571429, 0.07      , ..., 0.71286229, 0.40585322,
        0.16793744],
       [0.03571429, 0.45      , 0.075     , ..., 0.21974075, 0.40696371,
        0.48530014]])

In [ ]:
x_train.shape

(1760, 7)

In [ ]:
y_train.shape

(1760,)

STANDARIZATION


In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sst=StandardScaler()

In [ ]:
sst.fit(x_train)

StandardScaler()

In [ ]:
x_train=sst.transform(x_train)

In [ ]:
x_test=sst.transform(x_test)

In [ ]:
x_train

array([[-9.03426596e-01, -1.12616170e+00, -6.68506601e-01, ...,
         9.36586183e-01,  1.93473784e-01,  5.14970176e-03],
       [-3.67051340e-01,  7.70358846e-01, -5.70589522e-01, ...,
        -1.00470485e-01,  8.63917548e-01, -6.05290566e-01],
       [-1.17161422e+00,  5.89737842e-01, -4.53089028e-01, ...,
        -3.82774991e-01,  1.05029771e+00, -1.04580687e+00],
       ...,
       [-1.06433917e+00, -5.24091685e-01, -3.35588533e-01, ...,
        -8.98381379e-01, -6.34357580e-04, -4.37358211e-02],
       [-1.06433917e+00,  2.12501638e+00,  3.05234239e+00, ...,
         3.86340190e-01, -1.48467347e-01, -5.69036842e-01],
       [-5.01145154e-01,  7.40255346e-01, -5.11839275e-01, ...,
        -4.18045489e-01,  6.86860180e-01, -8.96531475e-01]])

In [ ]:
x_test

array([[ 1.34934948, -1.0960582 , -0.02225388, ...,  1.05232434,
        -0.37619899, -1.38984486],
       [ 1.26889319, -1.36698971,  0.05607978, ...,  0.67956909,
        -0.28013033, -0.96895253],
       [ 0.22296144,  0.25859933,  0.01691295, ...,  0.98974316,
         0.60209743,  0.22056087],
       ...,
       [ 1.88572474, -0.19295318, -0.62933977, ...,  0.35134079,
         1.61311363, -0.54905776],
       [ 1.75163092, -0.04243567, -0.57058952, ...,  0.1731198 ,
        -0.46741089, -0.64767698],
       [-1.22525175,  0.43922034, -0.55100611, ..., -1.74645651,
        -0.45817577,  0.95946086]])

TRAING THE MODEL


In [ ]:
p=LogisticRegression()

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
models = {
    'Logistic Regression': LogisticRegression(),

  'Naive Bayes':GaussianNB(),
  'Support Vector Machine':SVC(),
  'K-Nearest Neighbors':KNeighborsClassifier(),
  'Decision Tree':DecisionTreeClassifier(),
  'Random Forest':RandomForestClassifier(),
  'Bagging':BaggingClassifier(),
  'Adaboost':AdaBoostClassifier(),
  'Gradient Boosting':GradientBoostingClassifier(),
  'Extra Tress':ExtraTreeClassifier()



}
for name ,md in models.items():
  md.fit(x_train,y_train)
  ypred=md.predict(x_test)

  print(f"{name} with accuracy:{accuracy_score(y_test,ypred)}")


Logistic Regression with accuracy:0.9636363636363636
Naive Bayes with accuracy:0.9954545454545455
Support Vector Machine with accuracy:0.9681818181818181
K-Nearest Neighbors with accuracy:0.9568181818181818
Decision Tree with accuracy:0.9863636363636363
Random Forest with accuracy:0.9931818181818182
Bagging with accuracy:0.9840909090909091
Adaboost with accuracy:0.1409090909090909
Gradient Boosting with accuracy:0.9818181818181818
Extra Tress with accuracy:0.9181818181818182


In [ ]:
if x_train.shape[0] != y_train.shape[0]:
  print("x_train and y_train must have the same number of samples.")

In [ ]:
p=GaussianNB()
p.fit(x_train,y_train)
ypred=p.predict(x_test)
accuracy_score(ypred,y_test)

0.9954545454545455

In [ ]:
def recomend(N,P,K,temperature,humidity,ph,rainfall):
  features=np.array([[N,P,K,temperature,humidity,ph,rainfall]])
  prediction=p.predict(features).reshape(1,-1)
  return prediction[0]


In [ ]:
N=10
P=15
K=20
temperature=25
humidity=39
ph=35
rainfall=24
predict=recomend(N,P,K,temperature,humidity,ph,rainfall)
crop_dict={1:"Rice",
           2:"Maize",
           3:"Jute",
           4:"Cotton",
           5:"Coconut",
           6:"papaya",7:"Orange",8:"Apple"
           ,9:"MuskMelon",10:"WaterMelon",11:"Grapes",
           12:"Mango",13:"Banana",14:"Pomegranate",15:"Lentil",
           16:"BlackGram",17:"MungBean",18:"Mothbeans",19:"PigeonPeas",20:"Kidneybeans",21:"Chickpeas",22:"Coffee"}
if predict[0] in crop_dict:
  crop=crop_dict[predict[0]]
  print("{} is a best crop ".format(crop))
else:
  print("sorry no crop for this type of features")

Mothbeans is a best crop 


In [ ]:
!pip install flask_ngrok
!pip install pyngrok==4.1.1


  Preparing metadata (setup.py) ... done
  Created wheel for pyngrok: filename=pyngrok-4.1.1-py3-none-any.whl size=15964 sha256=311ffcd540a4fef8ccf7741e30d538c8b9cdf98f590255b39b323ec71fff43dd
  Stored in directory: /root/.cache/pip/wheels/4c/7c/4c/632fba2ea8e88d8890102eb07bc922e1ca8fa14db5902c91a8
Successfully built pyngrok


In [ ]:
from flask import Flask
from flask_ngrok import run_with_ngrok

In [ ]:
app=Flask(__name__)
run_with_ngrok(app)

In [ ]:
@app.route('/')
def index():
  return "<h1>hello world</h1>"
app.run()

 * Serving Flask app '__main__'
 * Debug mode: off


INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
INFO:werkzeug:Press CTRL+C to quit
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urll